### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by Leomonico** [lupuleasa-core/ValheimVanillaExpanded#1]
I am having an issue where every action item in the main menu show $menu_ before every button and won’t let me do anything at all

**Comment by lupuleasa-core** [comment]
Any screenshot?

Action item in main menu?

How did you install everything?

**Comment by Leomonico** [comment]
Give me a minute I’ll get a screenshot I just went to online in r2modman and installed just your mod pack and added manually forsaken and any portal

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Leomonico** [comment]
Thank you for your time.

Leo Anthony Monico

**Comment by lupuleasa-core** [comment]
I just made a new profile and downloaded same things, all looks good to me

have you created a new profile? maybe configs can mess you up

**Comment by lupuleasa-core** [comment]
also, search for "Any Portal Fix" there is a mod added for some fix apparently

**Comment by Leomonico** [comment]
Just did all of that and still same thing

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Leomonico** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: leo monico ***@***.***>
Sent: Tuesday, February 22, 2022 12:19:00 PM
To: leo monico ***@***.***>
Subject: RE: [lupuleasa-core/ValheimVanillaExpanded] Startup (Issue #1)


Okay I got it to work but now its like super zoomed out

Any tips





Thank you for your time.



Leo Anthony Monico

**Comment by lupuleasa-core** [comment]
try to change profile to a new one then

**Comment by Leomonico** [comment]
I did that but it’s like auto making the resolution to be 1920x1080 I only have 720p screen so I think it’s messing it up can’t find anything in the configs

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lupuleasa-core** [comment]
that is really weird, what happens when you try to run unmodded?

**Comment by Leomonico** [comment]
It stayed the same just now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lupuleasa-core** [comment]
then it is a problem with normal game install

try to start fresh

**Comment by Leomonico** [comment]
I got it all working now thanks for the help

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lupuleasa-core** [comment]
you should post what was the solution, so others know
